name = "the-board"
main = "src/index.js"
compatibility_date = "2024-01-01"

[[d1_databases]]
binding = "DB"
database_name = "the-board-db"
id = "8c6c08a1-c535-4dbe-b685-2108e0030edc"

[vars]
ENVIRONMENT = "production"
